# Generated by Django 4.2.11 on 2024-05-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_a', to='user.user')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_b', to='user.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b'), name='unique_friendship'),
        ),
    ]
