# Generated by Django 5.0.4 on 2024-05-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("album", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhotoTagMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="album.photo"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tags.tag"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="phototagmapping",
            constraint=models.UniqueConstraint(
                fields=("photo", "tag"), name="unique_photo_tag_mapping"
            ),
        ),
    ]
