# Generated by Django 5.0.4 on 2024-05-02 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0001_initial"),
        ("user", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
    ]
