# Generated by Django 5.0.4 on 2024-05-02 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0002_album_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="album_id",
            new_name="album",
        ),
    ]
