# Generated by Django 5.0.4 on 2024-05-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="hometown",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
